blank_issues_enabled: true
contact_links:
  - name: 👥 Discussions
    url:  https://github.com/ps-developers-sandbox/SARB-fundamentals/discussions/new/choose
    about: Please use discussions for issues that are not a bug, enhancement or feature request
